name: Claude Code on comments

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  run-claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Claude Code
        uses: anthropics/claude-code-action@v0
        with:
          trigger_phrase: "@claude"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
